### ISSUE TITLE
Exception when writing output to CSV

### ISSUE THREAD

**Issue by FuchsiaSoft** [hmol/LinkCrawler#15]
Just came across this when I enabled outputting to CSV on a website.

```
System.IndexOutOfRangeException was unhandled by user code
  HResult=-2146233080
  Message=Probable I/O race condition detected while copying memory. The I/O package is not thread safe by default. In multithreaded applications, a stream must be accessed in a thread-safe way, such as a thread-safe wrapper returned by TextReader's or TextWriter's Synchronized methods. This also applies to classes like StreamWriter and StreamReader.
  Source=mscorlib
  StackTrace:
       at System.Buffer.InternalBlockCopy(Array src, Int32 srcOffsetBytes, Array dst, Int32 dstOffsetBytes, Int32 byteCount)
       at System.IO.StreamWriter.Write(Char[] buffer, Int32 index, Int32 count)
       at System.IO.TextWriter.WriteLine(String value)
       at System.IO.TextWriter.WriteLine(String format, Object[] arg)
       at LinkCrawler.Utils.Outputs.CsvOutput.Write(IResponseModel responseModel) in C:\Users\Chris\Downloads\LinkCrawler-develop\LinkCrawler\LinkCrawler\Utils\Outputs\CsvOutput.cs:line 43
       at LinkCrawler.Utils.Outputs.CsvOutput.WriteInfo(IResponseModel responseModel) in C:\Users\Chris\Downloads\LinkCrawler-develop\LinkCrawler\LinkCrawler\Utils\Outputs\CsvOutput.cs:line 38
       at LinkCrawler.LinkCrawler.WriteOutput(IResponseModel responseModel) in C:\Users\Chris\Downloads\LinkCrawler-develop\LinkCrawler\LinkCrawler\LinkCrawler.cs:line 92
       at LinkCrawler.LinkCrawler.ProcessResponse(IResponseModel responseModel) in C:\Users\Chris\Downloads\LinkCrawler-develop\LinkCrawler\LinkCrawler\LinkCrawler.cs:line 59
       at LinkCrawler.LinkCrawler.<>c__DisplayClass31_0.<SendRequest>b__0(IRestResponse response) in C:\Users\Chris\Downloads\LinkCrawler-develop\LinkCrawler\LinkCrawler\LinkCrawler.cs:line 53
       at RestSharp.RestClientExtensions.<>c__DisplayClass1.<ExecuteAsync>b__0(IRestResponse response, RestRequestAsyncHandle handle)
       at RestSharp.RestClient.ProcessResponse(IRestRequest request, HttpResponse httpResponse, RestRequestAsyncHandle asyncHandle, Action`2 callback)
       at RestSharp.RestClient.<>c__DisplayClass3.<ExecuteAsync>b__0(HttpResponse r)
       at RestSharp.Http.ExecuteCallback(HttpResponse response, Action`1 callback)
       at RestSharp.Http.<>c__DisplayClass15.<ResponseCallback>b__13(HttpWebResponse webResponse)
       at RestSharp.Http.GetRawResponseAsync(IAsyncResult result, Action`1 callback)
       at RestSharp.Http.ResponseCallback(IAsyncResult result, Action`1 callback)
  InnerException: 

```

**Comment by hmol** [comment]
Could be hard to reproduce, but it looks like it's related to writing to the csv file. Any thoughts @NiklasHansen ? The exception is quite good when it suggests using `TextWriter.Synchronized()`, so maybe I will try that approach.

**Comment by hmol** [comment]
I just pushed an improvement of the write to csv-file functionality, think it should solve the problem.

**Comment by NiklasHansen** [comment]
I never thought of multiple threads being a problem, but I can see how it might turn into a problem, when also using ExecuteAsync in SendRequest. So using TextWriter.Synchronized() seems like the solution to me. This might hinder performance a little, as threads need to wait on the lock, but it might not be noticable.

**Comment by hmol** [comment]
yeah, other solution could be to utilize the [`ConcurrentQueue`](https://msdn.microsoft.com/en-us/library/dd267265%28v=vs.110%29.aspx), but it would require more work :smirk:
I think were good for now with `TextWriter.Synchronized()`
